/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    Header: typeof import('./src/components/meshwork/Header.vue')['default']
    Meshwork: typeof import('./src/components/meshwork/Meshwork.vue')['default']
    TimeBlock: typeof import('./src/components/meshwork/TimeBlock.vue')['default']
  }
}
